# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

# Install system dependencies and uv in one layer
RUN apk add --no-cache gcc musl-dev linux-headers curl && \
    curl -LsSf https://astral.sh/uv/install.sh | sh && \
    rm -rf /var/cache/apk/*

ENV PATH="/root/.local/bin:${PATH}"

WORKDIR /app

# Copy dependency files first for better layer caching
COPY pyproject.toml uv.lock* ./
COPY README.md ./
COPY src ./src

# Install Python package (src is needed for package build)
# uv automatically uses uv.lock if present for faster dependency resolution
RUN uv pip install --system --no-cache . || \
    (pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir .)

# Run the MCP server
CMD ["python", "-m", "duckduckgo_mcp_server.server"]
