# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-slim

WORKDIR /app

# Copy dependency files first for better layer caching.
COPY pyproject.toml ./
COPY README.md ./
COPY src ./src

# Install package via pip (without uv) to avoid flaky external installer.
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir .

# Run the MCP server.
CMD ["python3", "-m", "duckduckgo_mcp_server.server"]
